      <footer>
      &nbsp;&middot;&nbsp;<span class="TODO">Template</span> by <a href="http://techcofounders.com">Tech Co Founders</a>&nbsp;&middot;&nbsp;One Penn Plaza #6139, New York, NY 1
0119&nbsp;&middot;&nbsp;<br />

        &copy; 2012-2013 <span class="TODO">Company Name LLC</span>. All Rights Reserved. 
        <a id="privacy" href="#">Privacy Policy</a> and <a id="terms" href="#">Terms of Service</a>.
      </footer>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js""></script>
    <script type="text/javascript" src="/m/j/ga.js"></script>
    <script type="text/javascript" src="/m/j/default.js"></script>

